server:
  port: 8080
spring:
  application:
    name: store-portal
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
    register-with-eureka: true
    fetch-registry: true