spring:
  application:  # 应用名字，eureka 会根据它作为服务id
    name: store-eureka

---
spring:
  profiles: u1
eureka:
  instance:
    hostname: EurekaServerA
    lease-renewal-interval-in-seconds: 45
    lease-expiration-duration-in-seconds: 60
  client:
    service-url:
      defaultZone:  http://EurekaServerB:9091/eureka
    register-with-eureka: true
    fetch-registry: true
server:  # 服务端口
  port: 9090

---

spring:
  profiles: u2
eureka:
  instance:
    hostname: EurekaServerB
    lease-renewal-interval-in-seconds: 45
    lease-expiration-duration-in-seconds: 60
  client:
    service-url:
      defaultZone:  http://EurekaServerA:9090/eureka
    register-with-eureka: true
    fetch-registry: true
server:  # 服务端口
  port: 9091